Repository codestates-seb/seb41_main_023, pull requests merged in 2023-01, with the labels that each got.

#27 [FE] feat: 여행일정 페이지 구현
  client/.gitignore
  client/public/index.html
  client/src/App.js
  client/src/Components/itinerary/EditContainer.js
  client/src/Components/itinerary/InfoWindow.js
  client/src/Components/itinerary/PlaceInputBox.js
  client/src/Components/itinerary/PlanSection.js
  client/src/Components/itinerary/RenderMap.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Components/itinerary/StarRate.js
  client/src/Components/itinerary/TopNavigation.js
  client/src/Pages/Itinerary.js
  client/src/Pages/LoginPage.js
  client/src/Pages/SignUpPage.js
  client/src/index.css
  client/src/index.js
Labels: enhancement

#80 [FE]feat/travel plan
  client/package-lock.json
  client/package.json
  client/src/Components/itinerary/EditContainer.js
  client/src/Components/itinerary/PlaceInputBox.js
  client/src/Components/itinerary/PlanDropDown.js
  client/src/Components/itinerary/RenderMap.js
  client/src/Components/itinerary/SideDateBar.js
  client/src/Components/itinerary/SingleDate.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Components/itinerary/TopNavigation.js
  client/src/Pages/Itinerary.js
Labels: enhancement

#96 [FE]Feat/mapmarker
  client/src/App.js
  client/src/Components/budget/AddExpense.js
  client/src/Components/budget/Buget.js
  client/src/Components/budget/DateSelectBox.js
  client/src/Components/budget/PlaceSelectBox.js
  client/src/Components/itinerary/EditContainer.js
  client/src/Components/itinerary/InfoWindow.js
  client/src/Components/itinerary/MarkerLists.js
  client/src/Components/itinerary/PlaceInputBox.js
  client/src/Components/itinerary/PlanDropDown.js
  client/src/Components/itinerary/RenderMap.js
  client/src/Components/itinerary/SideDateBar.js
  client/src/Components/itinerary/SingleDate.js
  client/src/Components/itinerary/SinglePlan.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Components/itinerary/TopNavigation.js
  client/src/Pages/Itinerary.js
  client/src/Pages/WriteSingleBoard.js
Labels: enhancement

#104 [FE] css: 유저 프로필 & 프로필 수정 페이지 css 적용 및 html 수정
  client/src/App.js
  client/src/Components/Header.js
  client/src/Components/user/Modal.js
  client/src/Components/user/MyLogs.js
  client/src/Components/user/MyTrips.js
  client/src/Components/user/Tab.js
  client/src/Pages/Footer.js
  client/src/Pages/Main.js
  client/src/Pages/UserProfile.js
  client/src/Pages/UserProfileEdit.js
  client/src/index.css
Labels: enhancement

#105 Feat/movemarker
  client/src/App.js
  client/src/Components/AutoComplete.js
  client/src/Components/Board/SingleBoard/BoardSection.js
  client/src/Components/Board/SingleBoard/CommentSection.js
  client/src/Components/Board/SingleBoard/MapSection.js
  client/src/Components/Board/SingleBoard/Markers.js
  client/src/Components/Board/SingleBoard/SingleItinerary.js
  client/src/Components/Board/SingleBoard/TopSection.js
  client/src/Components/Calendar.js
  client/src/Components/budget/AddExpense.js
  client/src/Components/budget/Buget.js
  client/src/Components/budget/Category.js
  client/src/Components/budget/DateSelectBox.js
  client/src/Components/budget/DeleteExpense.js
  client/src/Components/budget/PlaceSelectBox.js
  client/src/Components/itinerary/EditContainer.js
  client/src/Components/itinerary/InfoWindow.js
  client/src/Components/itinerary/MarkerLists.js
  client/src/Components/itinerary/PlaceInputBox.js
  client/src/Components/itinerary/PlanDropDown.js
  client/src/Components/itinerary/PlanSection.js
  client/src/Components/itinerary/RenderMap.js
  client/src/Components/itinerary/SideDateBar.js
  client/src/Components/itinerary/SinglePlan.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Components/itinerary/TopNavigation.js
  client/src/Pages/Home.js
  client/src/Pages/Itinerary.js
  client/src/Pages/SingleBoard.js
Labels: enhancement

#116 [FE]Feat/Comment
  client/src/App.js
  client/src/Components/Board/SingleBoard/BoardSection.js
  client/src/Components/Board/SingleBoard/CommentSection.js
  client/src/Components/Board/SingleBoard/MapSection.js
  client/src/Components/Board/SingleBoard/Markers.js
  client/src/Components/Board/SingleBoard/SingleComment.js
  client/src/Components/Board/SingleBoard/SingleItinerary.js
  client/src/Components/Header.js
  client/src/Components/budget/AddExpense.js
  client/src/Components/budget/Buget.js
  client/src/Components/itinerary/PlanSection.js
  client/src/Components/itinerary/SinglePlan.js
  client/src/Components/user/Modal.js
  client/src/Components/user/Tab.js
  client/src/Pages/Itinerary.js
  client/src/Pages/LoadingPage.js
  client/src/Pages/LoginPage.js
  client/src/Pages/SignUpPage.js
  client/src/Pages/SingleBoard.js
  client/src/images/loading.gif
Labels: enhancement

#121 feat:comment 회원 제한 수정, 삭제 구현
  client/src/Components/Board/SingleBoard/CommentSection.js
  client/src/Components/Board/SingleBoard/SingleComment.js
Labels: enhancement

#124 [FE]Feat/comment pagination
  client/src/Components/Board/SingleBoard/CommentSection.js
  client/src/Components/Board/SingleBoard/SingleComment.js
  client/src/Components/Header.js
  client/src/Pages/LoginPage.js
  client/src/Pages/SignUpPage.js
  client/src/Util/Pagination.js
Labels: bug, enhancement

#141 [FE]Fix/debugging itinerary
  client/src/Components/Board/SingleBoard/CommentSection.js
  client/src/Components/Board/SingleBoard/MapSection.js
  client/src/Components/Board/SingleBoard/SingleComment.js
  client/src/Components/budget/AddExpense.js
  client/src/Components/budget/Buget.js
  client/src/Components/budget/DateSelectBox.js
  client/src/Components/budget/EditBudget.js
  client/src/Components/budget/EditExpense.js
  client/src/Components/budget/PlaceSelectBox.js
  client/src/Components/itinerary/EditContainer.js
  client/src/Components/itinerary/PlanSection.js
  client/src/Components/itinerary/SinglePlan.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Pages/EditSingleBoard.js
  client/src/Pages/Itinerary.js
  client/src/Pages/WriteSingleBoard.js
Labels: bug, enhancement

#155 [FE]Fix/delete plan
  client/src/Components/itinerary/TopNavigation.js
Labels: bug

#162 [FE]Fix/debugging
  client/src/Components/Board/Explore.js
  client/src/Components/Board/SingleBoard/TopSection.js
  client/src/Components/budget/AddExpense.js
  client/src/Components/budget/Buget.js
  client/src/Components/budget/Category.js
  client/src/Components/budget/EditBudget.js
  client/src/Components/budget/EditExpense.js
  client/src/Components/itinerary/PlanSection.js
  client/src/Components/itinerary/SinglePlan.js
  client/src/Components/itinerary/SinglePlanBox.js
  client/src/Components/itinerary/TopNavigation.js
  client/src/GlobalStyle.js
  client/src/Pages/Itinerary.js
  client/src/Pages/LoginPage.js
  client/src/Pages/SignUpPage.js
  client/src/Pages/SingleBoard.js
  client/src/Pages/UserProfile.js
  client/src/Pages/UserProfileEdit.js
Labels: bug, enhancement

#172 [FE]Fix/logmarker
  client/src/Components/Board/SingleBoardMarker.js
Labels: bug

#180 [FE]최신순, 좋아요순, 조회수순 탭 구현
  client/src/Components/Board/Explore.js
  client/src/Pages/Board.js
  client/src/Pages/Main.js
Labels: enhancement

#192 [FE]fix: debugging
  client/src/Components/AutoComplete.js
  client/src/Components/Board/Explore.js
  client/src/Pages/Board.js
  client/src/Pages/LoginPage.js
  client/src/Pages/SignUpPage.js
Labels: bug

#199 [main]fix:개행 버그 수정
  client/src/Components/Board/SingleBoard/BoardSection.js
  client/src/Components/Board/SingleBoard/SingleItinerary.js
  client/src/Pages/WriteSingleBoard.js
Labels: bug

#202 [Document]Doc/readme
  README.md
Labels: documentation
